# Generated by Django 3.0.5 on 2024-03-12 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0007_course_teacher'),
    ]


    operations = [
        migrations.AddField(
            model_name='course',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='question_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='total_marks',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
