# Generated by Django 3.0.5 on 2024-03-10 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_teacher_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='salary',
        ),
        migrations.AddField(
            model_name='teacher',
            name='email',
            field=models.EmailField(default=None, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teacher',
            name='profile_pic',
            field=models.ImageField(blank=True, default=2, upload_to='profile_pic/Teacher/'),
            preserve_default=False,
        ),
    ]
