# Generated by Django 3.0.5 on 2024-03-10 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_auto_20240311_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='email',
            field=models.EmailField(default='teacher@email.ru', max_length=254, null=True),
        ),
    ]
